### ISSUE TITLE
Help command is broken

### ISSUE THREAD

**Issue by WesCook** [Leviathan143/LootTweaker#10]
In the latest release of the mod (1.10.2-0.0.3), the `/help` is broken.  I'm unsure if this was fixed already along with the dump command (#9), as there's been no builds since then.

I thought I'd mention the issue just in case it wasn't known though.

**Comment by Leviathan143** [comment]
This was fixed in cb5b9d1cc3d8fa88d96fbb445b97c7f261b588db.
