### ISSUE TITLE
Script problem

### ISSUE THREAD

**Issue by scalda** [Leviathan143/LootTweaker#11]
Hi, 

I am wondering if you can tell me why my script keeps throwing the below error?
CraftTweaker-1.10.2-3.0.16.jar
LootTweaker-1.10.2-0.0.4.jar

`import loottweaker.vanilla.loot.LootTables;
import loottweaker.vanilla.loot.LootTable;
import loottweaker.vanilla.loot.LootPool;

val simple_dungeon = LootTables.getTable("minecraft:chests/simple_dungeon");

//simple_dungeon
simple_dungeon.removeItemEntry(<minecraft:bone>);`

[error](https://i.gyazo.com/64bc934eee8be99db2c33708eab661dc.png)

regards

scalda

**Comment by Leviathan143** [comment]
removeItemEntry is a method of LootPool, not LootTable. 
LootTables contain LootPools. LootPools contain LootEntries. Use *table*.getPool(*poolName*) to get a particular LootPool from a LootTable.

**Comment by scalda** [comment]
Thanks for that but I sorted it long before you replied to this

**Comment by bookerthegeek** [comment]
@scalda if you solve your own issue it is common courtesy to close it ypurself with the resolution for others incase they have the same issue.

Not being a complete fuck-tard to people who are helping you.

**Comment by Leviathan143** [comment]
@bookerthegeek Please do not use insults.
@scalda As booker said, it is common courtesy to leave the solution for others.
