### ISSUE TITLE
[Request] Pools, rolls, and cannonballs.

### ISSUE THREAD

**Issue by MechanosG** [Leviathan143/LootTweaker#14]
I'm not sure how to properly tag this as a request.  Am github narb.
---

I'd like to be able to modify a pool's roll variables easily, by a function.  And/or be able to create a new pool from a pool declared to a var/val.  I've been trying to find a way to do either of these for some hours now.  Alcohol got involved.  Not working out.  Plz send halp.  :)

Just in case I didn't make clear what I'm trying to do, I'm currently managing a modpack that is over-filling chest loot by a huge margin.  The roll chance on village chest loot is 5 to 14 times.  I don't know if that's vanilla or a mod's doing, but it's stuffing chests 100% full of loot, and I haven't been able to find a way to easily drop that 5-14 to something more...  manageable?

**Comment by Leviathan143** [comment]
>I'd like to be able to modify a pool's roll variables easily, by a function.

So you want to be able to modify an existing pools rolls and bonus rolls? I can make that possible.

> And/or be able to create a new pool from a pool declared to a var/val

You mean copying pools?

**Comment by MechanosG** [comment]
Yes to both.  On the 2nd quote, preferably with the option to set the rolls/bonus rolls and any other variables you'd normally set when creating a new pool, during the copy process.  Heh, your lightning fast response has kinda startled me.

**Comment by Leviathan143** [comment]
I'm working on this, but it's going to take a while. I need to do a bit of internal restructuring to make this possible. LootTweaker's internals are a bit complicated as loot tables don't load at the same time CraftTweaker executes its scripts.

**Comment by MechanosG** [comment]
Aight cool.  Thanks for the update and work involved.  It'll definitely be handy down the road.

**Comment by Leviathan143** [comment]
@MechanosG I'm scrapping the pool copying feature. It's just too complicated, mostly because I need to deep copy the conditions, entries, rolls and bonusRolls of the pool. This is not easy to do without the object being copied providing a method that copies it.

The ability to set rolls and bonusRolls was a simple addition and it's done, though unreleased.
