### ISSUE TITLE
Is there a function to import a vanilla like JSON loot table?

### ISSUE THREAD

**Issue by PrinceOfAmber** [Leviathan143/LootTweaker#20]
Adding loot tables the regular way you have something like below, this makes a bat drop a bat head ( player skin ).  Is there a direct way to import this JSON without rewriting scripts?

{
    "pools": [
		{
		"conditions": [
                {
                    "condition": "killed_by_player"
                },
                {
                    "condition": "random_chance_with_looting",
                    "chance": 0.02,
                    "looting_multiplier": 0.02
                }
            ],
            "rolls": 1,
            "entries": [
                {
                    "type": "item",
                    "name": "minecraft:skull",
                    "weight": 1,
                    "functions": [
                        {
                            "function": "set_data",
                            "data": 3
                        },
						{
                            "function": "set_nbt",
                            "tag": "{display:{LocName:\"Bat Head\"},SkullOwner:{Id:\"4ec40126-5a2d-4d6a-a0a3-125744548f0d\",Properties:{textures:[{Value:\"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmZmZDgwOGY4MTI3YjRhZDQ1OGQ5ZDJlMTgxYzY5MGFkZjQ4OWE2YWQzMmVlMmFhNGFjZmE2MzQxZmU4NDIifX19\"}]}}}"
                        }
                    ]
                }
            ]
        }
	]
}

**Comment by Leviathan143** [comment]
No. LootTweaker was built for the purpose of replacing JSON with ZenScript. This shouldn't be hard to convert anyway.

**Comment by Leviathan143** [comment]
Closing due to lack of reply
