### ISSUE TITLE
Minimum parameter of bonusRolls

### ISSUE THREAD

**Issue by Thyriel** [Leviathan143/LootTweaker#27]
1.12.2:
There's a slight error in your example script on the wiki github:

main.setBonusRolls(0, 2);
 throws an error in the logfile:

 

[INITIALIZATION][CLIENT][ERROR] Minimum parameter of bonusRolls must be greater than 0.0F!

Also some of the lines in the example script are missing an a linebreak so if you copy&paste the text there's 2 code lines behind a comment

**Comment by Leviathan143** [comment]
Thank you for the report.
