### ISSUE TITLE
Freeze when changing certain loottables

### ISSUE THREAD

**Issue by Thyriel** [Leviathan143/LootTweaker#29]
Please fill out **all** applicable sections in the template below:

**Description:**
When i edit the loottables of some entities the game freezes at "World loading" screen.
The script itself seems to work as it's working for a lot mobs and only some don't work.

**Steps to reproduce:**
- From the string array remove husk, magma_cube, stray, vex, ender_dragon and it works. I didn't test all of these 5 mobs one by one so i can't say for sure if it's all 5 causing the problem or only like 3-4 or them. (Ender dragon and at least 1 of the other 4 is causing the problem).
- The loot added is from Better questing mod + Standard expansion.
- Same freeze happens with every entity from mods (e.g. Twilight Forest bosses)

**Script Used**
https://pastebin.com/BxAJRxqP

**Version Info(Exact versions only):**  
LootTweaker-1.12-0.0.6.4

CraftTweaker2-1.12-4.0.8

Forge:14.23.0.2512

Minecraft: 1.12.2

**Logs and other useful information:**
nothing unusual in minecraft log / crafttweaker log (tables get added for the entities causing the freeze, no error)

**Comment by Leviathan143** [comment]
Post both logs anyway please

**Comment by Thyriel** [comment]
CT log: https://pastebin.com/72ZbvsBa
fml-client-latest (while game is in freezing state):  https://pastebin.com/huapNMni
**latest.log: https://pastebin.com/0x0MZGTb**

You where right, there is a java exception in latest.log caused by LootTweaker (but pretty strange that MC) this isn't there when i remove the 5 mobs from the script.

**Comment by Leviathan143** [comment]
I think I know what's wrong here. It should be a simple fix.

**Comment by Leviathan143** [comment]
This may be more difficult than I thought

**Comment by Leviathan143** [comment]
Bizarre, the tables that cause the issue are the tables with no pools in the first place. While that makes sense initially, LootTweaker has protections against pools that don't exist.
