### ISSUE TITLE
Script not being able to find loot table yet the command can find it ingame

### ISSUE THREAD

**Issue by Vyraal1** [Leviathan143/LootTweaker#32]
**Description:**
Using the command "/mt loottables byName immersiveengineering:chests/engineers_house" dumps the correct loot table json into the dumps folder, so I assumed this was the correct way to refer to the loot table with the script, however as shown in the script below I keep getting the error "No loot table with name immersiveengineering:chests/engineers_house" exists. 

I made sure that I was referring to the file name (as I verified that the loot pool is named differently for some reason).

**Script Used**
https://gist.github.com/Vyraal1/35d37617bfae3ca6829561a416e8560d

Immersive Engineering Loot Table
engineers_house.json 
https://gist.github.com/Vyraal1/bb720ab68e89a20d48c232b6679bfcf6

LootTweaker: 1.12-0.0.6.4
CraftTweaker 1.12-4.0.9
Forge 14.23.0.2531
Minecraft 1.12.2

**Comment by Leviathan143** [comment]
> as I verified that the loot pool is named differently for some reason

Loot pools can have any name. main and pool# are just the defaults that Forge uses if the creator hasn't named the pool. I'll look into this, though I suspect it's user error as the command finds loot tables the same way as scripts do. It's also possible that blu isn't registering the loot table early enough.

**Comment by Leviathan143** [comment]
I tested this and found that I was checking for the existence of the loot table before Blu registers it. It's perfectly reasonable for Blu to register the loot table when they do, so LootTweaker now checks later.

**Comment by Leviathan143** [comment]
Oh, also I'll probably make a release soon. There are quite a few fixes and a few features that I want to get out. As long as all the fixes are easily portable to the 1.10.2 and 1.11.2 branches, 0.0.7 should come out today.

**Comment by Vyraal1** [comment]
Thanks again! I'm going to make another issue regarding Abyssalcraft loot tables that I just ran into, but I appreciate on getting this issue worked out. I'll look forward to the release.
