### ISSUE TITLE
Abyssalcraft LootTables not being detected in the dump, not being found with /mt loottables

### ISSUE THREAD

**Issue by Vyraal1** [Leviathan143/LootTweaker#33]
Hey again,

So wasn't exactly sure if I should post this issue at Abyssalcraft's GitHub, here or both, but using /mt loottables dump doesn't seem to include any of the Abyssalcraft [LootTables](https://github.com/Shinoow/AbyssalCraft/tree/master/src/main/resources/assets/abyssalcraft/loot_tables). Also in my script I linked earlier, I got an error upon starting up a world saying that it couldn't find the anti_pig loot table for testing, and same as well for using /mt lootlootables byName.

 It might be AC's fault though as the RandomThing's Loot Generator (which I'm using to debug ingame) doesn't detect them either. Is there something I'm missing or appeal to Shinnow to get them registered differently?

**Comment by Leviathan143** [comment]
Which loot tables have you checked?

**Comment by Vyraal1** [comment]
Sorry meant /mt loottables all

**Comment by Leviathan143** [comment]
Right. Hmm

**Comment by Leviathan143** [comment]
Shinoow has fixed his on his end.
