### ISSUE TITLE
Random Things Item removal Error: Backing pool cannot be null!

### ISSUE THREAD

**Issue by lerokko** [Leviathan143/LootTweaker#35]
When trying to remove an item entry from random things from a loot table the following error message occurs: Backing pool cannot be null! Removing the entire pool works (meaning it gives the desired result of the item not generating in chests).

**How to replicate**
Use the script below together with LootTweaker and Random Things. When loading a save file the Error appears.

**Version Info (Exact versions only):**  
LootTweaker:  1.10.2-0.0.6.5
CraftTweaker:  1.10.2-3.0.26
Forge:  1.10.2 forge-12.18.3.2511
Minecraft:  1.10.2
Random Things: 1.10.2-3.7.7.1

**Logs, scripts and other useful information:** 

    import loottweaker.vanilla.loot.LootTables;
    import loottweaker.vanilla.loot.LootTable;
    import loottweaker.vanilla.loot.LootPool;
    import loottweaker.vanilla.loot.Conditions;
    import loottweaker.vanilla.loot.Functions;

    val simple_dungeon = LootTables.getTable("chests/simple_dungeon");

    val lavaCharm = simple_dungeon.getPool("randomthings:lavaCharm");
    lavaCharm.removeItemEntry(<randomthings:lavaCharm>);

**Note:**
The pools from random things all have only one entry each and the name is the same as the item which they generate.

**Comment by Leviathan143** [comment]
Thanks, I'll take a look.

**Comment by Leviathan143** [comment]
Welp, I've tracked down the issue and fixed it. Oddly enough I appear to have fixed it for 1.11 and 1.12 awhile ago, but I seem to have missed 1.10.2.
