### ISSUE TITLE
/mt loottables all not pulling animania loot tables

### ISSUE THREAD

**Issue by CKFrosty** [Leviathan143/LootTweaker#37]
Please fill out all applicable sections in the template below:

**Description:**  When I use /mt loottables all, I am not getting the loot tables for the Animania mod, which insists they have loot tables. 

**Steps to reproduce:**  use /my loottables with animania installed

**Version Info (Exact versions only):**  
LootTweaker:  0.0.6.5
CraftTweaker/Minetweaker: 3.0.26  
Forge:  13.20.1.2579
Minecraft:  1.11.2
Animania:1.4.3

**Comment by Leviathan143** [comment]
Animania has no loot tables, I've opened the .jar and checked. capnkirok/animania#95 seems to imply that loottables were added, but what actually seems to have been done is an update to animania's drops config. LootTweaker cannot help you here.

**Comment by CKFrosty** [comment]
OK, that's what it was looking like, but thank you!
