### ISSUE TITLE
[Question] Can't parse JSON. MalformedJsonException

### ISSUE THREAD

**Issue by Insane-96** [Leviathan143/LootTweaker#39]
I have this string
`jungleMain.addItemEntryHelper(<minecraft:bow>, 1, 0, [Functions.enchantWithLevels(1, 10, true), Functions.enchantRandomly(["infinity"]), Functions.enchantRandomly(["mending"]), Functions.parse("{\"function\": \"set_nbt\", \"tag\": \"{RepairCost:40,display:{Name:\\\"Bow of the Ancients\\\"}}\"}")], [Conditions.randomChance(0.8)]);`

I get MalformedJsonException: Expected name at line 1 column 2 path $

I've even tried with
`jungleMain.addItemEntryHelper(<minecraft:bow>, 1, 0, [Functions.enchantWithLevels(1, 10, true), Functions.enchantRandomly(["infinity"]), Functions.enchantRandomly(["mending"]), Functions.parse("{function: 'set_nbt',tag: '{RepairCost:40,display:{Name:\"Bow of the Ancients\"}}'}")], [Conditions.randomChance(0.8)]);`

same problem. I can't figure out what I'm doing wrong.

**Comment by Leviathan143** [comment]
You cannot use double quotes (") inside double quotes, even escaped. You must use single quotes (') instead of double quotes, then it will work. If you aren't already, use a text editor that has syntax highlighting. If the whole string doesn't have the right highlighting, it's unparseable.

**Comment by Insane-96** [comment]
Already tried something like this too
jungleMain.addItemEntryHelper(<minecraft:bow>, 1, 0, [Functions.enchantWithLevels(1, 10, true), Functions.enchantRandomly(["infinity"]), Functions.enchantRandomly(["mending"]), Functions.parse("{function: 'set_nbt',tag: '{RepairCost:40,display:{Name:\'Bow of the Ancients\'}}'}")], [Conditions.randomChance(0.8)]);
Without the " double quotes

**Comment by Leviathan143** [comment]
Stop escaping the quotes, it's unnecessary. Just use quotes.

**Comment by Insane-96** [comment]
Awesome. Thank you
