### ISSUE TITLE
[Request]Modify Villager/Merchant trades

### ISSUE THREAD

**Issue by Swerving** [Leviathan143/LootTweaker#44]
Villagers are infuriating when they sell a tool or item that the tweaker tried to make unobtainable, Especially trades added in by mods that sell redundant items that had their oredict and recipes removed.

**Comment by Leviathan143** [comment]
LootTweaker deals exclusively with loot tables. Villager trades do not use loot tables, hence this is out of scope for LootTweaker and will not be added.
A quick CurseForge search turned up [Villager Trade Tables](https://minecraft.curseforge.com/projects/villager-trade-tables), which looks like it should suit your needs.
