### ISSUE TITLE
[Crash] Game client crashed after adding loottweaker.

### ISSUE THREAD

**Issue by bontavi** [Leviathan143/LootTweaker#5]
MC - 1.10.2
Loottweaker - 0.0.1
Initial Inventory - 1.0.1
Forge - 12.18.3.220.2
Pastebin - http://pastebin.com/V6YCVKTF

I have added loottweaker to modpack and it crashed. By checking i have found that crash caused by these two mods - Loottweaker and Initial Inventory

**Comment by jaredlll08** [comment]
@Leviathan143 Loottweaker needs to check if the world has loaded before it does its stuff, I have a few mods that reload Crafttweaker before the world has loaded (preinit, init stuff), so they all crash with this).
A simple 
```
if(world !=null)
```
should do it

**Comment by Leviathan143** [comment]
@bontavi Sorry about leaving this for so long, github didn't notify me about it until Jared directly pinged me.
