### ISSUE TITLE
loottable dump command does not function with "target"

### ISSUE THREAD

**Issue by katubug** [Leviathan143/LootTweaker#68]
**Describe the bug**
Someone in the CrT discord reported that using `/ct loottables target` produced an "unknown error occurred." I tested it myself and found I had the same issue. This was tested with a very minimal modlist, and I do not believe any of the other mods are required to replicate.

Additionally, `/ct loottables all` functions without issue.

**To Reproduce**
1. Load into a creative world with LT and CrT present
2. Execute `/ct loottables target`

**Expected behavior**
I expected the animal under the crosshair to have its loottable produced in the `/dumps/` folder.

**Logs & scripts**
Logs are here: https://paste.ee/p/2z7Cc#PZa4h4J3mtKSXrocEr8UOcWy2aU0xSop

**Version Info (Exact versions only):**
LootTweaker: 0.1.4
CraftTweaker/Minetweaker: 4.1.20
Forge: 2847
Minecraft: 1.12.2

**Comment by Daomephsta** [comment]
Thanks for the report, it should be a simple fix.

**Comment by Daomephsta** [comment]
Thanks for the report, does [this JAR](https://drive.google.com/open?id=1_Wp4icGXt_kgPenPxOo_OlkMV-NaCa_Z) fix the issue?

**Comment by katubug** [comment]
Hello! Yes, just tested it in the same instance and I can confirm it's working as intended. :)
