### ISSUE TITLE
Cannot dump simple_dungeon table?

### ISSUE THREAD

**Issue by xJon** [Leviathan143/LootTweaker#69]
**Describe the bug**
I can't seem to be able to dump the `simple_dungeon` table data.
![bug](https://user-images.githubusercontent.com/8945347/73139251-b9741d00-4074-11ea-9994-79648f97c363.gif)
Command: `/ct loottables byName minecraft:chests/simple_dungeon`.

**Version Info (Exact versions only):**
LootTweaker: `0.1.5`
CraftTweaker: `4.1.20`
Forge: `14.23.5.2847`
Minecraft: `1.12.2`

Edit: same goes for `minecraft:chests/desert_pyramid `, `minecraft:chests/stronghold_library` & `minecraft:chests/jungle_temple`.
Is it because of a problematic mod? Is there any way of identifying which one without having to remove each one, load the game & see?

**Comment by Daomephsta** [comment]
@xJon Please provide a Minecraft log from a session where this issue occurred. 
When a command errors with "An unknown error occurred while attempting to perform this command", there is always critical information about the error in the log.

**Comment by xJon** [comment]
Oh, of course.
https://pastebin.com/P55nU6KE
Is there anything that can be done with this Mystcraft error?

**Comment by Daomephsta** [comment]
@xJon 
It's an issue on Mystcraft's side, they haven't defined how to dump their custom loot condition. There's nothing LootTweaker can do to fix it. Leave reporting it to me, looking at Mystcraft I'm unsure of its maintenance status.

**Comment by xJon** [comment]
Thank you! @Daomephsta 
I'll close this issue then.
