### ISSUE TITLE
Error Parsing

### ISSUE THREAD

**Issue by HerleyJLancaster** [Leviathan143/LootTweaker#72]
I made a script to remove bow, arrows and tipped arrows from the stray mob and to add Tconstruct bone arrows and wooden shortbow

"Error: [crafttweaker | SIDE_Client]: Error parsing Stray.zs:6 --: expected

The loot is still unadjusted

To Reproduce This is the script that I have written is here https://pastebin.com/fgvCSdvu

Expected behavior: remove/add loot to specified loot table

Logs & scripts CraftTweaker.log file is here https://pastebin.com/Mv2MHKYE

Version Info (Exact versions only): LootTweaker: 0.1.5+MC1.12.2 CraftTweaker/Minetweaker: Crafttweaker 4.1.20 Forge: 14.23.5.2847 Minecraft: 1.12.2 Tconstruct: 2.13.0.171

I'm still new to writing scripts and just started messing with the loottables

**Comment by Daomephsta** [comment]
Not a LootTweaker error, your ZenScript syntax is wrong. Double check that you pasted that script right, it's messed up in a lot of ways.

**Comment by HerleyJLancaster** [comment]
its copied right. I followed the LootTweaker guide for removing loot tables: https://pastebin.com/y6CtHk7Y with this example. I then got the items i wanted to remove/add in my in-game inventory and copied/pasted from the CraftTweaker log. i then replaced pig with stray and porkchop with arrow and a 2nd line with the tipped arrow and did the same with the other 2 i wanted to add from TConstruct. I also tried to simply remove the arrow: https://pastebin.com/1wAdG7yS with this example.

**Comment by Daomephsta** [comment]
You've misunderstood a lot about ZenScript syntax and how the loot system works. This isn't unexpected; learning ZenScript, object-oriented programming, and the loot table system with no prior experience is a lot. It doesn't help that resources on ZS are scarce.  
Please join [my discord](https://discordapp.com/invite/6DUqXDf) and I'll explain things in the morning. A real-time conversation will be far more effective for resolving this.
