### ISSUE TITLE
Help on clearing loot tables

### ISSUE THREAD

**Issue by Silivek** [Leviathan143/LootTweaker#81]
I can't for the life of me figure out how to remove all pools from these tables using the clear function, keep getting syntax errors and I can't figure out why. I know it's probably some stupidly simple thing but I still can't figure it out.
import loottweaker.LootTweaker;
import loottweaker.vanilla.loot.LootTable;
import loottweaker.vanilla.loot.LootTables;
import loottweaker.vanilla.loot.LootPool;

val mineshaft = LootTables.getTable("minecraft:chests/abandoned_mineshaft");
val pyramid = LootTables.getTable("minecraft:chests/desert_pyramid");
val end = LootTables.getTable("minecraft:chests/end_city_treasure");
val igloo = LootTables.getTable("minecraft:chests/igloo_chest");
val jungle = LootTables.getTable("minecraft:chests/jungle_temple");
val nether = LootTables.getTable("minecraft:chests/nether_bridge");
val dungeon = LootTables.getTable("minecraft:chests/simple_dungeon");
val corridor = LootTables.getTable("minecraft:chests/stronghold_corridor");
val crossing = LootTables.getTable("minecraft:chests/stronghold_crossing");
val library = LootTables.getTable("minecraft:chests/stronghold_library");
val blacksmith = LootTables.getTable("minecraft:chests/village_blacksmith");
val mansion = LootTables.getTable("minecraft:chests/stronghold_crossing");
val lostcity = LootTables.getTable("lostcities:chests/lostcitychest");
val raildungeon = LootTables.getTable("lostcities:chests/raildungeonchest");

mineshaft.clear();
pyramid.clear();
end.clear();
igloo.clear();
jungle.clear();
nether.clear();
dungeon.clear();
corridor.clear();
crossing.clear();
library.clear();
blacksmith.clear();
mansion.clear();
lostcity.clear();
raildungeon.clear();

**Comment by Daomephsta** [comment]
You have forgotten to include the error.

**Comment by Silivek** [comment]
Oh, okay. Whenever I try to run this script I get a "Error parsing filename.zs:21 --; expected" in the log file.

**Comment by Silivek** [comment]
I can't believe I'm so stupid. I don't know why but I just wasn't seeing what the error meant, I have it fixed now. Forgot a semicolon.
