### ISSUE TITLE
Reapeating NullPointerException?

### ISSUE THREAD

**Issue by Yourname942** [Leviathan143/LootTweaker#82]
**Describe the bug**
There is a repeating error message in my code which leads me to believe it will cause lag for us.

**To Reproduce**
1. I launch twitch App
2. Select my modpack (TLOSFReduxExtraBeef_1.0.8) 
3. Select play (purple gui button)
4. the minecraft launcher window appears
5. I select the correct version to launch
6. I launch Minecraft
7. loading of mods takes several minutes
8. I eventually crash (because of an unrelated issue with the mod: Embers Construct (that issue is resolved)

**Expected behavior**
I expect there to be no errors, and to not consistently and repeatedly give errors related to loottables.

**Logs & scripts**
latest log:
[latest.log](https://github.com/Daomephsta/LootTweaker/files/5042656/latest.log)
crash report:
[crash-2020-08-07_11.00.33-client.txt](https://github.com/Daomephsta/LootTweaker/files/5042663/crash-2020-08-07_11.00.33-client.txt)
crafttwaker log:
[crafttweaker.log](https://github.com/Daomephsta/LootTweaker/files/5042652/crafttweaker.log)

**Version Info (Exact versions only):**
LootTweaker: LootTweaker-0.2.0+MC1.12.2
CraftTweaker/Minetweaker: CraftTweaker2-1.12-4.1.20.574
Forge:  forge-14.23.5.2847
Minecraft: 1.12.2

**Additional context**
I fixed the unrelated crash issue with embers construct by settting B:dustStamping=false
Here are 4 other scripts that may be part of the problem:
located here: C:\Users\Greg\Twitch\Minecraft\Instances\TLOSFReduxExtraBeef_1.0.8\scripts|

[scripts.zip](https://github.com/Daomephsta/LootTweaker/files/5042726/scripts.zip)

**Comment by Daomephsta** [comment]
Closing as this was resolved by the answers to the questions you simultaneously asked in the Discord.
