### ISSUE TITLE
0.3.2 Crash on startup

### ISSUE THREAD

**Issue by brisingraerowing** [Leviathan143/LootTweaker#92]
**Describe the bug**
Crash on game startup

**To Reproduce**
1. Load 0.3.2
2. Start Game
3. Crash

**Expected behavior**
Game Loads

**Screenshots**
If applicable, add screenshots to help explain your problem. Do not screenshot text, link it as a file or paste it, in the next section.

**Logs & scripts**
[Crash Log](https://gist.github.com/brisingraerowing/63f23902976c747dfe26cf31b7af72a0)

**Version Info (Exact versions only):**
LootTweaker: 0.3.2
CraftTweaker: 4.1.20.698
Forge: 14.23.5.2860
Minecraft: 1.12.2

**Additional context**

**Comment by Daomephsta** [comment]
I've found and corrected the bug (4a567e66917cd28672ecc7b9b04ebf881de0a05e), then altered the code so it's extremely unlikely that kind of bug can happen again.
0.3.3 is now available on CurseForge with the fix.
<https://www.curseforge.com/minecraft/mc-mods/loottweaker/files/5092247>
