### ISSUE TITLE
0.4.0 update crash with Corail Tombstone on world loading

### ISSUE THREAD

**Issue by ghost** [Leviathan143/LootTweaker#94]
**Describe the bug**
Create a new world but failed to load it

**Logs & scripts**
https://mclo.gs/KLoy1SN

**Version Info (Exact versions only):**
LootTweaker:0.4.0
CraftTweaker:4.1.20.699
Corail Tombstone:4.6.6
Forge:14.23.5.2860
Minecraft:1.12.2

**Comment by Daomephsta** [comment]
Tombstone 4.6.7 changes the way Tombstone does loot, which seems to fix or avoid this issue.

Leave this issue open, as I think there may be a wider issue on LootTweaker's side. But for an immediate fix, update to Tombstone 4.6.7.

There will be log messages about duplicate loot names though. That's what LootTweaker crashes while trying to report with Tombstone 4.6.6.
LootTweaker fixes those for you, though ideally the mod author should fix them.

**Comment by Daomephsta** [comment]
Should be fixed by Daomephsta/Daomephsta-Loot-Shared@5ba3a4ef07325818ed89eace3f5b05c7ee5abede, but release is a way off

**Comment by ghost** [comment]
Thanks for the fix!
